### ISSUE TITLE
RSVP for an event after registration

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#18]
As someone who register for the event,  i should be able to RSVP for the event i registered for

` fn rsvp_for_event(ref self: TContractState, event_id: u256);`

update has_rsvp inside EventRegistration details to TRUE, 
this function should be call by someone who has register for the event.  
Write unit test 
- for the function rsvp_for_event
- check can only rsvp once
- check for emitted event

Provide an ETH

**Comment by codeZe-us** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Mid level Cairo Developer

### How I plan on tackling this issue
I will write a function that takes an event_id and the caller's address as parameters, then update the has_rsvp field in the EventRegistration details for the specified event_id to true. Also, I will make sure the function verifies if the caller has previously registered for the event before allowing the update. Finally, include the test for the function.

**Comment by casweeney** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking. I have also written and tested a more complex smart contract in Cairo that involves giving multiple token as rewards to user. See repo: https://github.com/casweeney/staking-multiple-reward-tokens

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.


### How I plan on tackling this issue
This task requires creating a function for registered user to RSVP for an event. I will first add the function signature in the IEvent interface, then implement the function that takes in the event_id, then I will check if the caller has registered for the event in which the id was passed, if true, I will update the `has_rsvp` property of the EventRegistration struct to TRUE.

**Comment by GideonBature** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
My name is Gideon Bature, I am a Software Engineer with experience in Rust, JavaScript, TypeScript and just concluded the Starknet Cairo bootcamp. Over the 8 weeks of the bootcamp I have written various smart contracts in cairo, which also includes writing both unit and integration tests using snfoundry. I have also written and emitted events in those smart contracts.

### How I plan on tackling this issue
From the description of the task, and after going through the repository, I am going to implement the `fn rsvp_for_event` function to first of all check if the `event_id` is present in the `event_registrations: Map<ContractAddress, u256>` storage of the smart contract to confirm if the person has registered for the event or not. As only someone that has registered for the event can RSVP.

Next, I am going to check the `attendee_event_details` in storage to see if the `has_rsvp` in the `EventRegistration` is `true`, since the person is suppose to only rsvp once.

If the `has_rsvp` is `true` then the function won't work, else, if it is `false`, it will be updated to `true`. I am also going to emit the `RSVPForEvent` event when both of these checks (assertions) passed.

Finally, I am going to write a unit test for the `rsvp_for_event` function to check that a person/contract address can only rsvp once. And also test for the emitted event to be sure that the event is properly emitted using the `spy_events()` method.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.


### How I plan on tackling this issue
 I will implement the rsvp_for_event function in the Events contract. This function will first validate that the caller is registered for the specified event_id by checking their address in the event_registrations storage mapping. If the caller is confirmed as a registered attendee, the function will update the has_rsvp field in the corresponding EventRegistration struct to true, indicating that they have officially RSVP'd for the event. To ensure the function's robustness, i also will write unit tests that verify that attendees can only rsvp once by checking the has_rsvp flag before allowing a change, as well as testing with the correct parameters upon successful execution. 

ETA - 2days

**Comment by Samuel1-ona** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

My background and how it can be leveraged
Hello a blockchain developer. I will love to work on this issue

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello @mubarak23, I would love to handle this...

### How I plan on tackling this issue
I will implement the function,
write relevant test

ETA: 6hrs

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello, I'm Dprof-in-tech, a seasoned Full Stack Blockchain Developer, and I'm excited to be part of ODHACK 9! I have a strong foundation in technologies such as Next.js, TypeScript, JavaScript, React, Node.js, Rust, and Cairo, I've built extensive experience across the blockchain development landscape.

I first got involved with OnlyDust during Edition 2, and since then, I've made 39 contributions across 11 different projects. Working on the platform has really helped me sharpen my skills, especially when it comes to delivering great solutions under tight deadlines. I love combining technical know-how with a user-focused approach, whether it's building immersive 3D experiences or crafting smart contracts that solve real-world problems.

Throughout, I've consistently demonstrated the ability to adapt and contribute effectively to diverse challenges. I'm confident in my ability to tackle new problems and drive innovation within the blockchain space. As we kick off ODHACK 9, I'm eager to apply my previous experience and technical expertise to push the boundaries of what's possible.

You can view my public profile on OnlyDust here: https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
Approach for Issue #18: RSVP for an Event after Registration

For this issue, i took a look at the contracts and i would approach a solution as such:

I would first complete the contract function to get the caller_ address, verify that the caller is registered for that event then update the has_rsvp field in the caller’s attendee registration details to true to show he / she has rsvp’ ed.

Now i would write the test cases with the below scopes:
	Verifying that the caller address is already registered for the event.
	Verifying  that the has_rsvp ‘ed field has a value of false to limit calling the 
            function more than once.
	Verifying that the has_rsvp ‘ed field was updated to true if false and all the          
            other conditions met.

My expected time of delivery would be 2-3 days from being assigned.
