### ISSUE TITLE
Event Details Function

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#19]
Given an eventId, the function should return the event details,

`fn event_details(self: @TContractState, event_id: u256) -> EventDetails;`

Write a unit test for the function and assert for each value in the `EventDetails` struct

Provide an ETH

**Comment by codeZe-us** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Mid level Cairo Developer

### How I plan on tackling this issue
I will write a function that takes an event_id as input and retrieves the event details from the event_details storage map, then make sure the function returns the complete EventDetails struct associated with the specified event_id. Also, include the test for the function.

**Comment by anonfedora** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
A fullstack Blockchain developer, with extensive experience in building Web3 dApps, governance systems using smart contracts.

### How I plan on tackling this issue
The goal is to create a funtion (event details) that read from the storage variable eventId that returns event details. The event details are stored in Starknet’s storage to ensure immutability and availability.

**Comment by casweeney** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.


### How I plan on tackling this issue
I will create a function that takes in an `event_id` as argument and with the `event_id` I will use it as a key to read the `event_details` mapping that returns the `EventDetails` struct.

For the test, I will first create an event, then I will call the function that returns EventDetails and assert that the details from the function matches with the details I used in creating the event.

**Comment by Akshola00** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I have a background in developing decentralized applications with Cairo for smart contracts on the StarkNet blockchain. I am experienced in building and deploying contracts and have a solid understanding of event-driven programming. I am familiar with Cairo testing and use of cairo cheatsheat, allowing me to write comprehensive tests that ensure contract reliability and security.

### How I plan on tackling this issue
I would first review the existing codebase to understand how events are stored and accessed. I would analyze the data structures to ensure efficient retrieval, consider the output format, and implement validation for invalid eventId inputs. After understanding the implementation, I would write unit tests to verify the function’s accuracy, ensuring it returns the correct details and handles edge cases properly.

**Comment by ryzen-xp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a Blockchain developer with expertise in Cairo, Solidity, Rust . I’ve contributed to open-source projects such as Worldcoin-Bridge-Linea and ArkProjectNFTs Bridge and more .

### How I plan on tackling this issue
[1]=>Make event_details function to return the details of an event based on the provided event ID.
[2]=>Write a unit test to assert that each value in the EventDetails struct is correctly returned.
[3]=>Ensure comprehensive test coverage to validate all fields in the EventDetails struct.
[4]=>Sir/Mam Please assign this issue to me .

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
i will Verify the function returns the correct event details,
Verify the function panics with the expected error message,
 Verify each field in the EventDetails struct:
owner
amount
event_type

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
 

I'm a Full Stack Blockchain Developer with demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development, complemented by Three.js for 3D experiences, and Solidity/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust, where I've made 83 significant contributions across 15 different projects since Edition 1. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements.  

With my deep experience in hackathon environments, I bring both technical excellence and practical development skills to the table. I'm confident I can contribute meaningfully to pushing the boundaries of what's possible in blockchain development while maintaining a focus on user-centric solutions. 

  

My profile (https://app.onlydust.com/u/Ugo-X) showcases my consistent ability to deliver results across various blockchain challenges. I'm excited to bring this experience and drive for innovation to your team. 

### How I plan on tackling this issue
I reviewed the contract function, and it’s nearly complete. My approach to solving this issue would be as follows:

1. I would ensure that all fields from the event details getter function are correctly fetching the value of their corresponding match.
2. I would write test cases that assert each return field’s value to verify that none return empty when a valid event_id is provided.
3. My expected delivery time would be 2-4 days.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am blockchain developer with experience in cario, typescript, java script, html, css react.My background in smart contract development equips me to effectively implement this functionality and validate it through thorough testing.

### How I plan on tackling this issue
To implement the `event_details` function, I would define it in the smart contract to return the details of an event based on the provided `event_id`. This function would retrieve and return the relevant data encapsulated in the `EventDetails` struct. For unit testing, I would create tests to assert that each value within the `EventDetails` struct is returned correctly, ensuring that the function accurately reflects the stored event data. Additionally, I would provision the necessary ETH in the testing environment.

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello, I'm Dprof-in-tech, a seasoned Full Stack Blockchain Developer, and I'm excited to be part of ODHACK 9! I have a strong foundation in technologies such as Next.js, TypeScript, JavaScript, React, Node.js, Rust, and Cairo, I've built extensive experience across the blockchain development landscape.

I first got involved with OnlyDust during Edition 2, and since then, I've made 39 contributions across 11 different projects. Working on the platform has really helped me sharpen my skills, especially when it comes to delivering great solutions under tight deadlines. I love combining technical know-how with a user-focused approach, whether it's building immersive 3D experiences or crafting smart contracts that solve real-world problems.

Throughout, I've consistently demonstrated the ability to adapt and contribute effectively to diverse challenges. I'm confident in my ability to tackle new problems and drive innovation within the blockchain space. As we kick off ODHACK 9, I'm eager to apply my previous experience and technical expertise to push the boundaries of what's possible.

You can view my public profile on OnlyDust here: https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
Approach for Issue #19: Event Details Function

I looked through the contract function and it was almost done. My approach to solving this issue would be as such:

1. I would make sure all fields from the event details getter function are fetching the value of its supposed match.
2. I would write test cases that assert for each value of the return fields to make sure they do not return empty when the event_id is valid.
3. My expected time of delivery would be 2-4 days.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will implement the `event_details` function, which will retrieve and return the details of an event based on the provided `event_id`. This function will access the contract's internal state to fetch the corresponding `EventDetails` struct, ensuring that users can obtain all relevant information about the specified event.

To ensure the correctness and reliability of this function, I will write a unit test that thoroughly checks each value in the `EventDetails` struct. This test will confirm that the function returns the expected results for various event IDs, verifying that all attributes, such as the event name, date, location, owner, and type, are accurate and properly populated.

Also, I will include scenarios in the test to handle cases where an invalid or nonexistent `event_id` is provided. This will help ensure that the function gracefully handles errors and returns appropriate responses, maintaining the integrity of the application. My ETA is 4days

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I'm a cairo developer with strong experience and I have contributed to several starknet projects on Only Dust.

### How I plan on tackling this issue
I'll implement the function and ensure it behaves as expected by writing a robust test to cover all edge cases.
