### ISSUE TITLE
Attendee Event Registration Details

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#24]
An an Attendee who register for an event, this function should return the event registration details, 

`
 fn attendee_event_details(self: @TContractState, event_id: u256) -> EventRegistration;`

Write unit test for the following case
- test function that assert each field in EventRegistration struct is return
- test the function caller has register for the event (event_id)

Provide an ETH

**Comment by ryzen-xp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a  Blockchain developer with expertise in Cairo, Solidity, Rust, and Foundry . I’ve contributed to open-source projects such as Worldcoin-Bridge-Linea and ArkProjectNFTs Bridge and more .

### How I plan on tackling this issue
[1]-Implement the attendee_event_details function to return event registration details.
[2]-Write unit tests to validate each field in the EventRegistration struct.
[3]-Ensure the function verifies the caller's registration for the specified event.
[4]-Provide an Ethereum address for test transactions where necessary.
[5]-Please Assign Me Sir ?

**Comment by danielrm2899** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am applying to this issue via OnlyDust platform. 

I have been working as a developer for over three years in Web 2 technologies, and since the beginning of this year, I have been learning and exploring Web 3.

### How I plan on tackling this issue
To address this issue, I would begin by thoroughly reviewing your code. I noticed that you have a test file, so I plan to align my approach with the structure and methodology you’ve already established there.

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
I will Test for the following:
Registered attendee: Verify the function returns the correct registration details.
Unregistered attendee: Verify the function panics with the expected error message.
Different attendee: Verify the function panics with the expected error message.
Registration details: Verify each field in the EventRegistration struct:
attendee
event_id
registration_time

**Comment by shaaibu7** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Smart contract developer with strong understanding of blockchain technology with experience in building tested and scalable smart contract and Dapp on the blockchain

### How I plan on tackling this issue
Write a unit test that calls the attendee_event_details function, passing a valid event_id.

Verify that the returned EventRegistration struct contains the expected details by asserting each field matches what was stored during registration.

Ensure that the test checks if the caller has registered for the event by verifying the function returns valid details only for registered attendees.

Add a case where the caller hasn't registered for the event, asserting that an error or default value is returned.

**Comment by Otaiki1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

My background and how it can be leveraged
I am a full-stack developer with experience in Python, Cairo, Solidity, React, and JavaScript.

How I plan on tackling this issue
I will write detailed unit  tests for the cases here

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a fullstack developer worked with various frontend frameworks over the years as well as different backend languages. currently transitioning into the web3 space.

### How I plan on tackling this issue
I will create a well documented and written codebase that will capture every bit of detail of the figma design and bring it to live, with the animations, mobile responsiveness, dark and light mode features as well as componentization for reusability across other pages, ican very much handle this task!

**Comment by Lukman-01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello! My name is Lukman, and I am a passionate Smart Contract Developer with two years of experience in writing smart contracts. My hands-on experience spans various blockchain platforms, including Ethereum and Starknet.

### How I plan on tackling this issue
To tackle this issue, I will start by analyzing the `attendee_event_details` function and the `EventRegistration` struct to understand the expected output and necessary fields. Next, I will set up the test environment by simulating an attendee registration for the specified event. After that, I will invoke the `attendee_event_details` function with the registered `event_id` and assert that each field in the returned `EventRegistration` struct matches the expected values. Finally, I will ensure that the function verifies the caller's registration status for the event, and I will run all tests to confirm that they pass successfully.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
 

I'm a Full Stack Blockchain Developer with demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development, complemented by Three.js for 3D experiences, and Solidity/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust, where I've made 83 significant contributions across 15 different projects since Edition 1. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements.  

With my deep experience in hackathon environments, I bring both technical excellence and practical development skills to the table. I'm confident I can contribute meaningfully to pushing the boundaries of what's possible in blockchain development while maintaining a focus on user-centric solutions. 

  

My profile (https://app.onlydust.com/u/Ugo-X) showcases my consistent ability to deliver results across various blockchain challenges. I'm excited to bring this experience and drive for innovation to your team. 

### How I plan on tackling this issue
 went through the smart contracts and looking at the event registration details contract, i would write its test function as such:

I would write the test to cover checking to see that the attendee event details are populated and do not return empty when a valid event_id is initialized.
I would make sure the scope also covers checking that the attendee is fully registered for the event before getting their registration details.
My expected time of delivery would be 2-3 days from the day of being assigned

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
My background in smart contract development and testing equips me to ensure the contract functions correctly and meets all requirements for retrieving event registration details.

### How I plan on tackling this issue
To implement the `attendee_event_details` function and write unit tests, I would first define the function within the smart contract to retrieve event registration details associated with the given `event_id`, returning an `EventRegistration` struct. Then, I would create unit tests to assert that each field in the struct is correctly returned, ensuring the function caller is validated as a registered attendee for the specified event. Additionally, I would provision the necessary ETH in the test environment to facilitate testing.

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello, I'm Dprof-in-tech, a seasoned Full Stack Blockchain Developer, and I'm excited to be part of ODHACK 9! I have a strong foundation in technologies such as Next.js, TypeScript, JavaScript, React, Node.js, Rust, and Cairo, I've built extensive experience across the blockchain development landscape.

I first got involved with OnlyDust during Edition 2, and since then, I've made 39 contributions across 11 different projects. Working on the platform has really helped me sharpen my skills, especially when it comes to delivering great solutions under tight deadlines. I love combining technical know-how with a user-focused approach, whether it's building immersive 3D experiences or crafting smart contracts that solve real-world problems.

Throughout, I've consistently demonstrated the ability to adapt and contribute effectively to diverse challenges. I'm confident in my ability to tackle new problems and drive innovation within the blockchain space. As we kick off ODHACK 9, I'm eager to apply my previous experience and technical expertise to push the boundaries of what's possible.

You can view my public profile on OnlyDust here: https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
Approach for Issue #24: Attendee Event Registration Details

I went through the smart contracts and looking at the event registration details contract, i would write its test function as such:

I would write the test to cover checking to see that the attendee event details are populated and do not return empty when a valid event_id is initialized.
I would make sure the scope also covers checking that the attendee is fully registered for the event before getting their registration details.
My expected time of delivery would be 2-3 days from the day of being assigned.
