### ISSUE TITLE
Unregistered for an Event

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#58]
As user who has register for an event, i should be able to unregistered for the event, 

write a function that allow user to unregistered for the event, only user has register for an event can unregistered

emit UnregisteredEvent event for backend to consume.

refer to register_for_event function for details. 

**write end to end unit test for the function.** 

**NOTE: ONLY APPLICATIONS VIA ONLYDUST WILL BE CONSIDERED, 
DESCRIBE IN DETAILS HOW YOU INTEND TO HANDLE THIS ISSUE .**

**Comment by ikemHood** [comment]
Can I get on this?

**Comment by amJoe-dev** [comment]
Would love to tackle this, I have experience Woking on similar projects

**Comment by omsant02** [comment]
i would like to take this issue

i would add an UnregisterEvent struct and a function unregister_event in the events contract that checks attendee_events_details mapping to verify registration and emit an event

**Comment by ikemHood** [comment]
Hey @mubarak23, Can I get on this?
I am a fullstack web3 software developer with 3 years of experience and I am already very familiar with the codebase.

I would remove the user from the event_registration map and decrement the count of registered users for the event, then emit an Unregistered event so that the backend and also watch that and reflect possible changes from the datebase

**Comment by obacollins-lab** [comment]
Could I take over this issue? I'm a new contributor to this project

**Comment by Emmanex01** [comment]
May I be assigned to this? Please

**Comment by raizo07** [comment]
Kindly assign me to work on this?

**Comment by No-bodyq** [comment]
May I try my hand at this?
